#!/bin/sh
# get the authority
# 1.open BIOS and setting virtual techonoligy open
# intall VirtualBox:
# 1.download VirtualBox in the https://www.virtualbox.org
# 2.continue next step to instll utill finish it
# config VirtualBox:
# 1.hotkey 'ctrl+G' ,disply preferences window
# 2.in general setting machine fold : D:\Vbpc  then press ok!
# 3.new PC create: robin linux ubuntu(64-bits)
# 4.setting memory is 1/2(2048M) host memory
# 5.create a virtual hard disk now
# 6.choice VDI
# 7.dynamically allocated
# 8.press next
# install ubuntu:
# 1.download from https://www.ubuntu.com/download/desktop
# 2.continue press next is ok
##install extension package
# 1. install extension in host PC
# 2. run guest PC and eject disk
# 3. press 设备-->安装增强功能（这样屏显和共享文件夹才能正常）******

##change default color of terminal
##Edit->preferences->custom Font 'MonoSpace Regular 14'
##colors: background is solarized and palette is solarized

##update and upgrade linux
#sudo apt-get update
#sudo apt-get upgrade

##mount shared path to home
#in virtual-box add setting -> shared fold NOT auto-mount
#mkdir /home/robin/workspace
#in /etc/fstab  add "workspace  /home/robin/workspace  vboxsf  defaults 0  0"
##if umount path
#sudo umount -f /home/robin/workspace

########################################
##add shared file mode to user Robin
#whoami
##:robin
#cat /etc/group | grep vbox
##:vboxsf:x:999:robin
#sudo usermod -a -G vboxsf robin
########################################


#copy config file from shared path
#cp -r /media/sf_other/conf_ubt ./
#if want to execute the file
#chmod +x conf_ubt
#./conf_ubt

#sudo apt-get install ack wmctrl vim vim-gnome guake meld astyle
##dos and unix format switch
#sudo apt-get install dos2unix
##install git
#sudo apt-get install git-core

##install yahei_consolas_hybird(1st way)
#git clone https://github.com/GitHubNull/YaHei-Consolas-Hybrid-1.12.git &&\
#    sh YaHei-Consolas-Hybrid-1.12/setup.sh &&\
#    cd - && rm -rf YaHei-Consolas-Hybrid-1.12
##(2nd way)
#cp workspace/install/old/YaHei.Consolas.1.12.ttf /usr/share/fonts
#cd /usr/share/fonts
#mkfontscale
#mkfontdir
#check message：
#fc-list :lang=zh

##install univeral-ctags
#sudo apt-get install automake autoconf pkg-config
#mkdir ~/library
#cd ~/library &&\
#git clone https://github.com/universal-ctags/ctags &&\
#cd ctags &&\
#./autogen.sh
#./configure
#make
#make install
#rm -rf ~/library/ctags

##install vim plugin
#put .vimrc into /home/robin

#copy c-support.zip
# mkdir .vim
#cd .vim
#mkdir plugged
#cp workspace/install/c-support.zip ./
# unzip c-support.zip
##install vim-plug
#sudo apt-get install curl
#curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

##install youcompleteMe
#sudo apt-get install minicom
#sudo apt install build-essential cmake python3-dev
#cd ~/.vim/plugged &&\
#git clone https://github.com/Valloric/YouCompleteMe.git
#cd YouCompleteMe &&\
#git submodule update --init --recursive
#python3 install.py --clang-completer

#config guake terminal
#preference->appearance->font:Monospace 14 & schemes:Monokai
#guake open when pc start
#startup application->add /usr/bin/guake

##install gcc-arm-none-eabi
##(should NOT install apt-get for not the latest one, for printf not working)
#sudo cp workspace/install/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 ./library
#cd library &&\
#tar -jxvf ./gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 -C ./
## linux 64bits 要兼容 arm 32bits
#sudo apt-get install lsb-core libc6-i386
##add path to /etc/profile
#sudo gvim /etc/profile
#add "export PATH=$PATH:/home/robin/library/gcc-arm-none-eabi-5_4-2016q3/bin" in the end
#source /etc/profile
##check install success
#when press "arm-" the press tab key, then display "arm-none-eabi"

#install libusb
#first way
#sudo apt-cache search libusb
#sudo apt-get install libusb-1.0-x
#second way
#sudo cp -r /media/sf_other/libusb-1.0.22.tar.bz2 ./library
#tar -jxvf libusb-1.0.22.tar.bz2
#cd library/libusb-1.0.22
#./configure
#make
#sudo make install

#install openocd
#first way
#sudo apt-cache search openocd
#sudo apt-get install openocd libusb++-dev
#second way
#sudo cp -r /media/sf_other/openocd-0.10.0.zip ./library
#unzip openocd-0.10.0.zip
#cd library/openocd-0.10.0
#./configure
#make
#sudo make install

#======================================================
#need check these related App
#sudo apt-get install lib32ncurses5 lib32tinfo5 libc6-i386
#sudo apt-get install build-essential pkg-config autoconf automake libtool libusb-dev libusb-1.0-0-dev libhidapi-dev
#sudo apt-get install libtool libsysfs-dev
#======================================================

## handle images
#sudo apt-get install shutter

##handle website
#sudo apt-get install ruby
#sudo gem install jekyll
#sudo apt-get install python-pip
#pip install pyments

#install yahei_consolas_hybird in gvim

## install gif make
#sudo add-apt-repository ppa:djcj/hybrid
#sudo apt-get update
#sudo apt-get install ffmpeg

## install gif make
#sudo add-apt-repository ppa:peek-developers/stable
#sudo apt update
#sudo apt install peek

