#!/bin/sh
# get the authority
# 1.open BIOS and setting virtual techonoligy open
# intall VirtualBox:
# 1.download VirtualBox in the https://www.virtualbox.org
# 2.continue next step to instll utill finish it
# config VirtualBox:
# 1.hotkey 'ctrl+G' ,disply preferences window
# 2.in general setting machine fold : D:\Vbpc  then press ok!
# 3.new PC create: robin linux ubuntu(64-bits)
# 4.setting memory is 1/2(2048M) host memory
# 5.create a virtual hard disk now
# 6.choice VDI
# 7.dynamically allocated
# 8.choice 40GB
# 9.press next
# install ubuntu:
# 1.download from https://www.ubuntu.com/download/desktop
# 2.continue press next is ok
##install extension package
# 1. install extension in host PC
# 2. run guest PC and eject disk
# 3. press 设备-->安装增强功能（这样屏显和共享文件夹才能正常）******

##change default color of terminal
##Edit->preferences->custom Font 'MonoSpace Regular 14'
##colors: background is solarized and palette is solarized

##update and upgrade linux
#sudo apt-get update
#sudo apt-get upgrade

##mount shared path to home
#in virtual-box add setting -> shared fold NOT auto-mount
#mkdir /home/robin/workspace
#in /etc/fstab  add "ubuntu  /home/robin/workspace  vboxsf  defaults 0  0"
##if umount path
#sudo umount -f /home/robin/workspace

#copy config file from shared path
#cp workspace/install/conf_ubt ./

#sudo apt-get install ack wmctrl vim vim-gnome guake meld astyle
##dos and unix format switch
#sudo apt-get install dos2unix
##install git
#sudo apt-get install git-core

##install yahei_consolas_hybird(1st way)
#git clone https://github.com/GitHubNull/YaHei-Consolas-Hybrid-1.12.git &&\
#    sh YaHei-Consolas-Hybrid-1.12/setup.sh &&\
#    cd - && rm -rf YaHei-Consolas-Hybrid-1.12
##(2nd way)
#cp workspace/install/old/YaHei.Consolas.1.12.ttf /usr/share/fonts
#cd /usr/share/fonts
#mkfontscale
#mkfontdir
#check message：
#fc-list :lang=zh

##install univeral-ctags
#sudo apt-get install automake autoconf pkg-config
#mkdir library
#cd library &&\
#git clone https://github.com/universal-ctags/ctags
#cd ctags &&\
#./autogen.sh
#./configure
#make
#sudo make install
#cd
#rm -rf library/ctags

##copy vimrc to home
#cp workspace/install/.vimrc ./

##copy c-support.zip
#mkdir .vim &&\
#cd .vim &&\
#mkdir plugged
#cp -r ../workspace/install/c-support.zip ./
#unzip c-support.zip
#cp -r ../workspace/install/templates/ ./
##install vim-plug
#sudo apt-get install curl
#curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

##install youcompleteMe
#sudo apt-get install minicom
#sudo apt install build-essential cmake python3-dev
#cd .vim/plugged &&\
#git clone https://github.com/Valloric/YouCompleteMe.git
#cd YouCompleteMe &&\
#git submodule update --init --recursive
#python3 install.py --clang-completer

##update and upgrade linux
#sudo apt-get update
#sudo apt-get upgrade
##install vim plugin
##gvim the input":PlugInstall"
##copy a.vim into plugged
#cp -r workspace/install/a.vim .vim/plugged

#config guake terminal
#preference->appearance->font:Monospace 14 & schemes:Monokai
#guake open when pc start
#startup application->add /usr/bin/guake

##reboot the PC

##install gcc-arm-none-eabi
##(should NOT install apt-get for not the latest one, for printf not working)
#sudo cp -r workspace/install/gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 ./library
#cd library &&\
#tar -jxvf ./gcc-arm-none-eabi-5_4-2016q3-20160926-linux.tar.bz2 -C ./
## linux 64bits 要兼容 arm 32bits
#sudo apt-get install lsb-core libc6-i386
##add path to /etc/profile
#sudo gvim /etc/profile
##add "export PATH=$PATH:/home/robin/library/gcc-arm-none-eabi-5_4-2016q3/bin" in the end
##source /etc/profile
##check install success
##when press "arm-" the press tab key, then display "arm-none-eabi"

##install libusb
#sudo apt-cache search libusb
#sudo apt-get install libusb-1.0-0-dev

##install openocd
#sudo apt-cache search openocd
#sudo apt-get install openocd libusb++-dev
#sudo cp workspace/install/jlink-swd.cfg /usr/share/openocd/scripts/interface

## handle images
#sudo apt-get install shutter

##handle website
#sudo apt-get install ruby
#sudo gem install jekyll
#sudo apt-get install python-pip
#pip install pyments

#install yahei_consolas_hybird in gvim

## install gif make
#sudo add-apt-repository ppa:djcj/hybrid
#sudo apt-get update
#sudo apt-get install ffmpeg

## install gif make
#sudo add-apt-repository ppa:peek-developers/stable
#sudo apt update
#sudo apt install peek

